# Generated by Django 5.2.3 on 2025-06-12 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tipo',
        ),
    ]
