# Generated by Django 5.2.3 on 2025-06-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_manager', '0002_remove_producto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='estado',
            field=models.CharField(max_length=50),
        ),
    ]
