# Generated by Django 5.2.3 on 2025-06-12 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_manager', '0003_alter_maquina_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='entrenador_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gym_manager.empleado'),
        ),
    ]
